#!/bin/bash
echo "The current directory is:";
curdir=`pwd`;
echo $curdir;
for ((i=a; a<3; a++))
do
echo "Enter file name";
read file_name;
if [ -f $file_name ];
then echo "File exist";
date -r $file_name +%F;
echo "Enter date (YYYY-MM-DD):";
read var_date;
date -d $var_date +%F &>/dev/null
if [ $? -eq 0 ];
then if [ "`date -d "$var_date" +%F`" \> "`date -r "$file_name" +%F`" ];
then echo "File has not changed";
else echo "File has changed";
fi
fi
break;
else echo "File does not exist" && echo " ";
fi
done



